spring:
  datasource:
    url: postgresql://dpg-d7tjt6i8qa3s73c74p2g-a.oregon-postgres.render.com:5432/animeflix
    username: postgresql
    password: jcsucJj3ahL2TiWNZE93tNEfqrXhkWhM
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  port: 8083

app:
  jwt:
    secret: change-this-secret-key-change-this-secret-key
    expiration-ms: 86400000
